# Intro to Pandas
by Ryan Orsinger

## Module 3: DataFrames Continued

### Pandas DataFrames Continued - Identifying Missing Values
- Identifying and counting missing values
- Removing rows with missing information
- Dropping columns from a DataFrame

In [ ]:
import pandas as pd

In [ ]:
# Let's generate some data with missing values.
# Real world data often has missing values
df = pd.DataFrame([
    {
        "item": "crackers",
        "serving_size": "4 crackers",
        "calories": 10,
        "fat": "1.1g",
        "sodium": "125mg",
        "price": 2.99,
        "discount": None
    },
    {
        "item": "club soda",
        "serving_size": "8 oz",
        "calories": None,
        "fat": None,
        "sodium": "75mg",
        "price": 2.25,
        "discount": None

    },
    {
        "item": "apple",
        "serving_size": 2,
        "calories": 95,
        "fat": None,
        "sodium": None,
        "price": 1.99,
        "discount": None
    },
    {
        "item": "banana",
        "serving_size": 3,
        "calories": 105,
        "fat": "0.4g",
        "sodium": "1mg",
        "price": None,
        "discount": None
    },
    {
        "item": "spam",
        "serving_size": "1 tin",
        "calories": None,
        "fat": None,
        "sodium": None,
        "price": None,
        "discount": None
    }
])

# Set the index to be the item name
df.set_index("item", inplace=True)
df

          serving_size  calories   fat sodium  price discount
item
crackers    4 crackers      10.0  1.1g  125mg   2.99     None
club soda         8 oz       NaN  None   75mg   2.25     None
apple                2      95.0  None   None   1.99     None
banana               3     105.0  0.4g    1mg    NaN     None
spam             1 tin       NaN  None   None    NaN     None

In [ ]:
# The .info method outputs data types and non-null value count
df.info()

In [ ]:
# Notice that missing values in a numeric column show as NaN, which means "not a number"
# For more on NaN, see https://en.wikipedia.org/wiki/NaN
df.calories

In [ ]:
# NaN exists to allow us to do math without getting execution errors
# Many math functions ignore NaNs
df.calories.mean()

In [ ]:
# By default, .value_counts ignores NaNs, too
df.sodium.value_counts()

In [ ]:
# Use dropna=False to count missing values
df.sodium.value_counts(dropna=False)

In [ ]:
# Notice that missing values in a string/object column show as None
df.fat

In [ ]:
# .isna() can operate on a column, returning a boolean series
df.sodium.isna()

In [ ]:
# .isna() can also operate on the entire dataframe
df.isna()

In [ ]:
# Counting the number of nulls by column
print("Number of nulls by column")
df.isna().sum()

In [ ]:
print("Proportion of nulls by column")
df.isna().mean()

In [ ]:
# Counting the number of nulls by row
# Recall that .sum can run on columns or by row, by row with axis=1
print("Number of nulls by row")
df.isna().sum(axis=1)

In [ ]:
# Proportion of the number of nulls by row
# Recall that .sum can run on columns or by row, by row with axis=1
print("Proportion of nulls by row")
df.isna().mean(axis=1)

### Handling Missing Values
- There's no one right answer for all cases.
- "It depends" is a common answer in data science. Context matters.
- Sometimes missing values might mean zero, depending on the context, so we can fill in zero.
- Sometimes, dropping entire rows or columns is appropriate
- Sometimes, filling missing values makes sense to keep the rest of the row or column's data

In [ ]:
# Example of removing null values
# dropna drops every row with a null value
# Since there is missing data in every row, this is quite destructive...
# the default axis argument is axis=0, which means row-wise
df.dropna()

In [ ]:
# dropna(axis=1) drops all columns with any missing values
# This is also too destructive to be helpful
df.dropna(axis=1)

In [ ]:
# Let's review the dataframe
df

In [ ]:
# The discount column is adding no information here, so we can drop it
df.drop(columns="discount", inplace=True)
df

In [ ]:
# Reassign the df
# df.drop(index=["spam"], inplace=True) would produce the same result
df = df[df.index != "spam"]
df

## Additional Resources
- [.isnull](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html) is an alias for `isna`.
- The [.value_counts](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) documentation
- [Pandas .isna documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.isna.html)

## Exercises
- Use `pd.read_csv` to read `"penguins.csv"` into a dataframe variable named `penguins`
- Write the pandas code to count the number of missing values by column
- Write the pandas necessary to get the proportion of missing values by row. Store this to a variable named `percent_missing_by_row`
- Sort the `percent_missing_by_row` series in descending order. How many of the rows are mostly empty?

In [ ]:
# upload dataset file
# Open Files tab
# Select upload
# Choose and open penguins.csv file downloaded in your system.
from google.colab import files
uploaded = files.upload()

Saving penguins.csv to penguins.csv

In [ ]:
# Use `pd.read_csv` to read `"penguins.csv"` into a dataframe variable named `penguins`
pen = pd.read_csv("penguins.csv")
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Use .isna to count the number of missing values by column
missing_col = pen.isna().sum()
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Write the pandas necessary to get the proportion of missing values by row.
# Store this to a variable named `percent_missing_by_row`
missing_row_percent = pen.isna().mean(axis=1)
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Sort the `percent_missing_by_row` series in descending order
# How many of the rows are mostly empty
missing_row_percent = missing_row_percent.sort_values(ascending=False)
empty_rows = (missing_row_percent > 0.5).sum()
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Return shape before removing null values
pen.shape
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# removing null values. Inplace=True makes this change permanent
pen.dropna(inplace=True)
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Return shape after removing null values
pen.shape
pen

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009